
version: "3.7"
services:
  install-node:
    build:
      context: ./
      dockerfile: DockerFile
      args:
        - buildno=1
        - gitcommithash=cdc3b19
    volumes:
      - vnode:/usr/src/fe-mfa
  app-snps:
    environment:
      - NODE_ENV=production
    build:
      context: ./
      dockerfile: ./packages/app-snps/DockerFile
      args:
        - buildno=1
        - gitcommithash=cdc3b19
    volumes:
      - type: volume
        source: vnode
        target: /usr/src/app-snps
        volume:
          nocopy: true
    depends_on:
      - install-node
    links:
      - install-node
volumes:
  vnode:

 